name: beacons_school
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_beacon: ^0.5.1
  fluttertoast: ^8.0.7
  icons_plus: ^4.0.0
  permission_handler: ^10.2.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/image/
